# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0002_insertcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='user',
        ),
    ]
