# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0003_remove_query_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='query_text',
            new_name='application',
        ),
        migrations.AddField(
            model_name='query',
            name='function',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
