# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0005_auto_20170329_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='app_description',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='function_description',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='language',
            field=models.CharField(default='None', max_length=20),
            preserve_default=False,
        ),
    ]
