# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0008_feedback_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='code',
        ),
        migrations.AddField(
            model_name='feedback',
            name='query',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='searchApp.Query'),
            preserve_default=False,
        ),
    ]
