# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0009_auto_20170424_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_search',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
