# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0012_auto_20170424_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_search',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchApp.Code'),
        ),
    ]
