# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0014_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_search',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchApp.Query'),
        ),
    ]
